apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helmapp 
  namespace: helm-flux
spec:   
  interval: 1m 
  chart:
    spec: 
      chart: helm-webapp
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m