apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespaceName }}
  labels:
    app: {{ .Values.appName }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.appName }}
  type: {{ .Values.service.type }}